config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "loot_tables#index"

  resources :loot_tables do
    resources :loot_items
    resources :rolls, only: [:create]
  end
end

app/models/loot_item.rb
class LootItem < ApplicationRecord
  belongs_to :loot_table
  belongs_to :inner_table, optional: true, class_name: "LootTable"

  validates :name, presence: true
  validates :probability, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :min, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :max, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: :min }

  def quantity
    return min if min == max
    min + rand(1 + max - min)
  end

  def to_s
    "LootItem id: #{id}, name: #{name}"
  end
end

app/controllers/loot_items_controller.rb
class LootItemsController < ApplicationController
  before_action :get_loot_table
  before_action :get_tables, only: %i[ new edit update create ]
  before_action :set_loot_item, only: %i[ show edit update destroy ]

  # GET /loot_items or /loot_items.json
  def index
    @loot_items = @loot_table.loot_items
  end

  # GET /loot_items/1 or /loot_items/1.json
  def show
  end

  # GET /loot_items/new
  def new
    @loot_item = @loot_table.loot_items.build
  end

  # GET /loot_items/1/edit
  def edit
  end

  # POST /loot_items or /loot_items.json
  def create
    @loot_item = @loot_table.loot_items.build(loot_item_params)

    respond_to do |format|
      if @loot_item.save
        format.html { redirect_to loot_table_path(@loot_table), notice: "Loot item was successfully created." }
        format.json { render :show, status: :created, location: @loot_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loot_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loot_items/1 or /loot_items/1.json
  def update
    respond_to do |format|
      if @loot_item.update(loot_item_params)
        format.html { redirect_to loot_table_path(@loot_table), notice: "Loot item was successfully updated." }
        format.json { render :show, status: :ok, location: @loot_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loot_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loot_items/1 or /loot_items/1.json
  def destroy
    @loot_item.destroy!

    respond_to do |format|
      format.html { redirect_to loot_table_path(@loot_table), notice: "Loot item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loot_item
      @loot_item =@loot_table.loot_items.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loot_item_params
      params.require(:loot_item).permit(:name, :probability, :loot_table_id, :always, :unique, :inner_table_id, :min, :max)
    end

    def get_loot_table
      @loot_table = LootTable.find(params[:loot_table_id])
    end

    def get_tables
      if @loot_table
        @tables = LootTable.where.not(id: @loot_table.id)
      else
        @tables = LootTable.all
      end
    end
end

app/helpers/loot_items_helper.rb
module LootItemsHelper
end

app/views/loot_items/_form.html.erb
<%= form_with(model: [@loot_table, loot_item], local: true, class: "my-4 flex flex-col gap-4") do |form| %>
  <% if loot_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(loot_item.errors.count, "error") %></h2>

      <ul>
        <% loot_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :probability, style: "display: block" %>
    <%= form.number_field :probability, min: 0 %>
    <p class="text-sm p-2">
      This is relative probability compared to the rest of the loot items on the table.
      A 10 here and another item with a 10 probability would give equal chance to both items.
    </p>
  </div>

  <div>
    <p class="text-">Quantity</p>
    <div class="flex items-center gap-1">
      <%= form.label :min, style: "display: block" %>
      <%= form.number_field :min, min: 1 %>
      to
      <%= form.number_field :max, min: 1 %>
      <%= form.label :max, style: "display: block" %>
    </div>
  </div>

  <div class="flex items-center gap-1">
    <%= form.check_box :always %>
    <%= form.label :always, style: "display: block" %>
    <p class="text-sm p-2">
      Always include this item in the results, overriding the probability.
      This will override the inner_table.
    <p>
  </div>

  <div class="flex items-center gap-1">
    <%= form.check_box :unique %>
    <%= form.label :unique, style: "display: block" %>
    <p class="text-sm p-2">
      Only ever include one of these in the results. Ignores items from the inner table.
    <p>
  </div>

  <div>
    <%= form.label :inner_table, style: "display: block" %>
    <%= form.select :inner_table_id, @tables.collect{|t| [t.title, t.id]}, :include_blank => true %>
    <p class="text-sm p-2">
      If this item is rolled, instead roll on the selected table.
      This is overridden by the Always option.
    <p>
  </div>
  
  <div class="flex items-center gap-5">
    <%= form.submit class: "p-2 bg-teal-300 hover:bg-teal-400 cursor-pointer rounded" %>
    <%= link_to "Cancel", loot_table_path(@loot_table) %>
  </div>
<% end %>

app/views/loot_items/_loot_item.html.erb
<div id="<%= dom_id loot_item %>" class="flex gap-4">
  <p><%= loot_item.name %></p>
  <p>P: <%= loot_item.probability %></p>

  <%= link_to "Edit", edit_loot_table_loot_item_path(@loot_table, loot_item) %> |
  <%= button_to "Destroy", [@loot_table, loot_item], method: :delete %>

</div>

app/views/loot_items/edit.html.erb
<h2 class="text-xl">Editing loot item</h2>

<%= render "form", loot_item: @loot_item %>

app/views/loot_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Loot items</h1>

<div id="loot_items">
  <% @loot_items.each do |loot_item| %>
    <%= render loot_item %>
    <p>
      <%= link_to "Show this loot item", loot_item %>
    </p>
  <% end %>
</div>

<%= link_to "New loot item", new_loot_item_path %>

app/views/loot_items/new.html.erb
<h2 class="text-xl">New Loot Item</h2>

<%= render "form", loot_item: @loot_item %>

app/views/loot_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @loot_item %>