config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "loot_tables#index"

  resources :loot_tables do
    resources :loot_items
    resources :rolls, only: [:create]
  end
end

app/controllers/loot_tables_controller.rb
class LootTablesController < ApplicationController
  before_action :set_loot_table, only: %i[ show edit update destroy ]

  # GET /loot_tables or /loot_tables.json
  def index
    @loot_tables = LootTable.all
    @show_item_actions = false
  end

  # GET /loot_tables/1 or /loot_tables/1.json
  def show
    @show_item_actions = true
    @roll = Roll.new
  end

  # GET /loot_tables/new
  def new
    @loot_table = LootTable.new
  end

  # GET /loot_tables/1/edit
  def edit
  end

  # POST /loot_tables or /loot_tables.json
  def create
    @loot_table = LootTable.new(loot_table_params)

    respond_to do |format|
      if @loot_table.save
        format.html { redirect_to loot_table_url(@loot_table), notice: "Loot table was successfully created." }
        format.json { render :show, status: :created, location: @loot_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loot_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loot_tables/1 or /loot_tables/1.json
  def update
    respond_to do |format|
      if @loot_table.update(loot_table_params)
        format.html { redirect_to loot_table_url(@loot_table), notice: "Loot table was successfully updated." }
        format.json { render :show, status: :ok, location: @loot_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loot_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loot_tables/1 or /loot_tables/1.json
  def destroy
    @loot_table.destroy!

    respond_to do |format|
      format.html { redirect_to loot_tables_url, notice: "Loot table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loot_table
      @loot_table = LootTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loot_table_params
      params.require(:loot_table).permit(:title)
    end
end

app/helpers/loot_tables_helper.rb
module LootTablesHelper
end

app/views/loot_tables/_form.html.erb
<%= form_with(model: loot_table, class: "my-4 flex flex-col gap-4") do |form| %>
  <% if loot_table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(loot_table.errors.count, "error") %></h2>

      <ul>
        <% loot_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="flex items-center gap-5">
    <%= form.submit class: "p-2 bg-teal-300 hover:bg-teal-400 cursor-pointer rounded" %>
    <%= link_to "Cancel", @loot_table %>
  </div>
<% end %>

app/views/loot_tables/_loot_table.html.erb
<div id="<%= dom_id loot_table %>" class="flex flex-col gap-2">

  <table class="w-full table-auto border border-slate-400">
    <thead>
      <tr>
        <th class="border border-slate-300 p-2 bg-slate-100">Name</th>
        <th class="border border-slate-300 p-2 bg-slate-100">Probability</th>
        <th class="border border-slate-300 p-2 bg-slate-100">Min</th>
        <th class="border border-slate-300 p-2 bg-slate-100">Max</th>
        <th class="border border-slate-300 p-2 bg-slate-100">Always</th>
        <th class="border border-slate-300 p-2 bg-slate-100">Unique</th>
        <th class="border border-slate-300 p-2 bg-slate-100">Inner Table</th>
        <% if @show_item_actions %>
          <th class="border border-slate-300 p-2 bg-slate-100"></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% for loot_item in loot_table.loot_items %>
        <% @loot_table = loot_table %>
        <tr>
          <td class="border border-slate-300 p-2"><%= loot_item.name %></td>
          <td class="border border-slate-300 p-2"><%= loot_item.probability %></td>
          <td class="border border-slate-300 p-2"><%= loot_item.min %></td>
          <td class="border border-slate-300 p-2"><%= loot_item.max %></td>
          <td class="border border-slate-300 p-2"><%= loot_item.always ? "✔" : "" %></td>
          <td class="border border-slate-300 p-2"><%= loot_item.unique ? "✔" : "" %></td>
          <td class="border border-slate-300 p-2">
              <% if loot_item.inner_table_id %>
                <%= link_to loot_item.inner_table.title, loot_table_path(loot_item.inner_table), class: "underline" %>
              <% end %>
          </td>
          <% if @show_item_actions %>
            <td class="border border-slate-300 p-2">
              <div class="flex gap-1 items-center">
                <%= link_to "Edit", edit_loot_table_loot_item_path(@loot_table, loot_item), class: "p-1 rounded bg-yellow-400 hover:bg-yellow-500 text-sm" %>
                <%= button_to "Destroy", [@loot_table, loot_item], method: :delete, class: "p-1 rounded text-red-500 hover:text-red-600 text-sm font-bold", data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/loot_tables/edit.html.erb
<h2 class="text-xl">Editing loot table</h2>

<%= render "form", loot_table: @loot_table %>

app/views/loot_tables/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="rounded-xl p-4 bg-gray-100 my-5">
  <p>
    This is a project inspired by <a class="underline" href="https://www.codeproject.com/Articles/420046/Loot-Tables-Random-Maps-and-Monsters-Part-I">Loot-Tables, Random Maps and Monsters - Part I</a>
    by Mike (Prof. Chuck). Here you'll find a Random Distribution System (RDS) that implements most of the features of the article.
  </p>

  <p class="mt-4">
    Create a loot table that represents all the possible loot from an encounter. Each loot item in the table has a chance to drop relative to all the other items in the table. Roll on the table to generate a set of items. Items can be other tables, unique across the whole result, randomly distribute the amount (for gold or similar), or always be part of the result.
  </p>

  <p class="mt-4">
    There is currently no way to hook into the tables and items to change them on the fly.
  </p>

  <p class="mt-4 flex gap-1">
    Check out the project on
    <a class="flex gap-1" href="https://github.com/ericworkman/RDSCalculator">
      GitHub
      <svg class="h-5 w-5" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>GitHub</title><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>
    </a>.
  </p>
  
</div>

<h2 class="text-xl">Loot Tables</h2>

<%= link_to "New loot table", new_loot_table_path, class:"block my-4 p-2 bg-blue-600 text-white w-48 text-center rounded-lg" %>

<div id="loot_tables" class="grid lg:grid-cols-2 gap-4">
  <% @loot_tables.each do |loot_table| %>
    <div class="p-3 rounded-lg border border-1 border-gray-300 flex flex-col shadow-md">
      <%= link_to loot_table.title, loot_table, class: "text-xl mb-3" %>

      <%= render loot_table %>
    </div>
  <% end %>
</div>

app/views/loot_tables/new.html.erb
<h2 class="text-xl">New Loot Table</h2>

<%= render "form", loot_table: @loot_table %>

app/views/loot_tables/roll.turbo_stream.erb
  <%= turbo_stream.replace dom_id(@loot_table, "roll") do %>
    <div id="<%= dom_id(@loot_table, 'roll') %>">
      <p class="text-xl">You rolled</p>
        <% if @rolled_items.length < 1 %>
          <p>None</p>
        <% end %>
        <% for item in @rolled_items %>
          <p><%= item.count %> <%= item.name %><p>
        <% end %>
    </div>
  <% end %>

app/views/loot_tables/show.html.erb
<p style="color: green"><%= notice %></p>

<h3 class="text-xl"><%= @loot_table.title %></h3>

<div class="flex gap-3 mb-4 items-center">
  <%= link_to "Edit", edit_loot_table_path(@loot_table), class: "p-2 rounded bg-yellow-400 hover:bg-yellow-500 text-sm" %>
  <%= button_to "Destroy", @loot_table, method: :delete, class: "p-2 rounded text-red-500 hover:text-red-600 text-sm font-bold", data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
  <%= link_to "Back", loot_tables_path, class: "text-sm" %>
</div>

<%= render @loot_table %>

<div class="flex gap-4 mt-1">
  <%= link_to "Add Loot Item", new_loot_table_loot_item_path(@loot_table), class: "p-2 rounded bg-indigo-300 hover:bg-indigo-400 hover:text-white text-sm" %>
</div>

<div class="mt-5 flex flex-col">
  <%= render "rolls/form", roll: @roll %>

  <div class="h-16 mt-1">
    <div id="<%= dom_id(@loot_table, 'roll') %>" ></div>
  </div>
</div>